### ISSUE TITLE
CMake can not find Qt5Multimedia

### ISSUE THREAD

**Issue by alf000** [Sky-Meyg/Celeste#1]
``` CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):

  Could` not find a package configuration file provided by "Qt5Multimedia"
  with any of the following names:

    Qt5MultimediaConfig.cmake
    qt5multimedia-config.cmake

  Add the installation prefix of "Qt5Multimedia" to CMAKE_PREFIX_PATH or set
  "Qt5Multimedia_DIR" to a directory containing one of the above files.  If
  "Qt5Multimedia" provides a separate development package or SDK, be sure it
  has been installed. 
```

System:
Linux alflaptop 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Relevant packages installed:
libqt5multimedia5/bionic,now 5.9.5-0ubuntu1 amd64 [installed]

**Comment by alf000** [comment]
Fixed by installing:
sudo apt-get install qttools5-dev

**Comment by herbmillerjr** [comment]
The dependency in particular here is `qtmultimedia5-dev`. Note you will also need `libqt5textospeech5-dev`. These will be listed in the documentation soon.
