### ISSUE TITLE
Backport to Qt 5.9

### ISSUE THREAD

**Issue by herbmillerjr** [Sky-Meyg/Celeste#2]
Some distributions that aren't yet EOL are on an older Qt version. Many are on 5.9, some may even be on 5.7. Create some conditional logic that allows Celeste to build against these versions of Qt (even at the risk of lost functionality).

Reported by @alf000.

**Comment by alf000** [comment]
Output from top error when running make command:
/usr/include/c++/8/bits/unordered_map.h:228:28: error: use of deleted function ‘std::hash<QString>::hash()’

Full output from make:
[build.log](https://github.com/Sky-Meyg/Celeste/files/5404534/build.log)

I dont know if this error a product of the change from QRandom.

**Comment by herbmillerjr** [comment]
It's not related to `QRandom` but it is related to backporting to Qt 5.9. `QString` doesn't have a template specialization for `std::hash` until Qt 5.14.

**Comment by alf000** [comment]
Yeah, sorry I should have included the compiler
`g++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
`
